### ISSUE TITLE
Loved the event, here's some feedback

### ISSUE THREAD

**Issue by FreddyMSchubert** [42core-team/connection#63]
**I was asked for feedback, here you go. Didn't know where to put it, but this is the library, right?**

![customer-feedback](https://github.com/user-attachments/assets/76d0b1a3-519b-49fb-a21a-bbe88a22cce1)

1. Should the focus be providing players with the fewest possible functions & then they have to build themselves a little lib, or to have them go right into strategizing? Because stuff like `ft_distance` exists (handholdey) but creating new units is super annoying because you don't get passed back the unit. I understand this is because you need to request a new unit from the server, which takes some time, longer than you can halt the function execution for. Can you reserve an `id` instead, and add an initialized boolean into `t_obj`? That way, we already have a reference to the new `t_obj`, even though we can't use it just yet. My larger point being, this library sometimes feels very handholdey and sometimes makes you do a lot of work to work around the limitations of the library to achieve simple things. Either way is fine, but i think being handholdey would be better as than you can fully focus on strategy. For another example of something really complicated which in my eyes wouldn't have had to be, please reference point 6.
2. Why create an initializer for a unit that allows us to pass in a config if we can't mess with the config? It's just kind of confusing.
3. Just a balancing thing, but I believe workers were too strong at attacking other players. I believe that only spawning workers would have been a viable strategy because of this, especially seeing as the workers cost almost half as much as the warriors. But maybe I'm just salty I was killed by workers. The tradeoff between spending less money but getting a less powerful unit feels like it should be made more clear.
4. I think more resource data functions are required. As far as I can see, the only info available is what resource is closest to a given `t_obj`, but that eliminates any sort of planning or strategy beyond just walking to the closest resource and mining it. (But that might just be me not getting something). In general, a function that retrieves all objects currently on the board regardless of obj type would have been nice, to solve that problem in general. (I really wanted to make a resource heatmap.)
5. Why do some of the functions not have `ft_` in front of them lol just a nitpick don't worry about it.
6. Finally, the fact pointers to a `t_obj` may not be consistent between loop calls should have been made more clear, either in the wiki or by explicitly telling us. That was a bit frustrating. We created a seperate `custom_obj` list to save custom data about each unit, but sometimes, the `t_obj` would just be at some completely random huge unsigned long value in the next loop iteration. _We went insane bro._ If pointers can't be turned to be persistent, at least `ft_get_obj_by_id` needs to exist please, thanks. I don't want to loop through all of my enemies, opponent enemies, cores, and you can't even loop through resources. And this fact needs to be at the top of the wiki in red bold H1 sized letters.

**Ok I see how that might feel very negative but that was really me just picking out all of the negative points, the entire event was really awesome. I'd love to help if you'd have me, but I really don't want to not be able to compete in the next event haha.**

![images](https://github.com/user-attachments/assets/5bac156a-2f9b-42ae-8b05-b251a063ccce)

**Comment by Reptudn** [comment]
loving that feedback <3

We will try to address all those issues you had. Would be nice if you open individual issues to each of those topics or comment those which already address your issues.

**Comment by FreddyMSchubert** [comment]
@Reptudn Where do I post 2 and 3? I've posted the other stuff in seperate repos.

Also, I don't think an issue is required for these, but allowing cpp in the future would be great. I understand we can't submit makefiles, that would create security concerns, but just checking what file endings are in the submitted srcs and choosing a makefile accordingly should be pretty simple if you decide that's a thing you want to do.
Also please asan thanks.
Just please ask your teammates about it on the next meeting, thanks.

**Comment by PaulicStudios** [comment]
Thank you for that much feedback!
I replied to all issues individually.

Balancing will always be an issue. For the next changes we will take this into consideration. Adding new units and features will through over the whole balancing we already did -.-

For post 2 you can create an issue in the current repo that we just remove the function.
