### ISSUE TITLE
Better resource functions

### ISSUE THREAD

**Issue by FreddyMSchubert** [42core-team/connection#65]
I think more resource data functions are required. As far as I can see, the only info available is what resource is closest to a given t_obj, but that eliminates any sort of planning or strategy beyond just walking to the closest resource and mining it. (But that might just be me not getting something). In general, a function that retrieves all objects currently on the board regardless of obj type would have been nice, to solve that problem in general. (I really wanted to make a resource heatmap.)

Full Feedback -> https://github.com/42core-team/connection/issues/63

**Comment by PaulicStudios** [comment]
I think you oversaw there something in the docs. There is a game object which contains everything you see on the map. You can iterate over that to get everything you need. All the ft_get functions do the same.
```
typedef struct s_game
{
	/**
	 * @brief The status of the game. Can be OK, PAUSED, END or WAIT_FOR_CLIENTS.
	 */
	t_status status;
	/**
	 * @brief The config contains base informations about the game that don't change like the map size and the unit types.
	 */
	t_config config;
	/**
	 * @brief The id of the team that you are playing for.
	 */
	unsigned long my_team_id;
	/**
	 * @brief List of all teams and their informations. The array is terminated by an element with id 0.
	 */
	t_team *teams;
	/**
	 * @brief List of all cores and their informations. The array is terminated by an element with id 0.
	 */
	t_obj *cores;
	/**
	 * @brief List of all resources and their informations. The array is terminated by an element with id 0.
	 */
	t_obj *resources;
	/**
	 * @brief List of all units and their informations. The array is terminated by an element with id 0.
	 */
	t_obj *units;
	/**
	 * @brief List of all actions that will be send to the server when your function ends.
	 */
	t_actions actions;
} t_game;

```
